import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>검색어를 입력하여 검색해보세요.</p>
          <div>
            <a href="https://www.syu.ac.kr/cse/" target="_blank" rel="noopener noreferrer">
              By{" "}
              <img
                src="https://www.syu.ac.kr/cse/wp-content/themes/syu-hakbu/images/logo/logo_w.png"
                alt="logo"
                width={100}
                height={24}
              />
              컴퓨터공학부
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <input
            placeholder="검색어를 입력하세요"
            style={{ fontSize: 40, padding: 8, position: "absolute", zIndex: 1, maxWidth: "80vw" }}
          />
        </div>

        <div className={styles.grid} />
      </main>
    </>
  );
}
